version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: infoscribe-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - infoscribe-network

  builder:
    image: infoscribe-flask:latest
    container_name: infoscribe-builder
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - infoscribe-network

  server:
    image: infoscribe-express:latest
    container_name: infoscribe-server
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - infoscribe-network

volumes:
  mysql-data:

networks:
  infoscribe-network:
    driver: bridge
